name: azul_ruben_dario_libro_gratis
description: Libro azul de Rubén Darío gratuito.
version: 1.2.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_markdown:
  share:
  url_launcher:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/md/